### ISSUE TITLE
help file 

### ISSUE THREAD

**Issue by pascalkrautm** [pascalkrautm/002---Audio-News-Podcast-Generator#12]
For the purpose of support, we should still create a helper class and describe the helper. By pressing` h`, for example, the user should get the most important information

**Comment by Matadore3** [comment]
Helper file was created and can be taken from the helper.py file. The whole thing was stored object oriented. No tuning necessary so far

**Comment by pascalkrautm** [comment]
helper_description = ("",
                              "To generate the RSS feed, you need to answer several questions."
                              "Below are these questions with their purpose for clarification and understanding:",
                              "-In the first step you need to enter your desired topics so that the present program"
                              " can search the Internet according to your entered interests.",
                              "-You will then be asked whether you want the news to be generated as a pdf, MP3 or"
                              " voice-speak. If you choose the pdf or MP3 variant, please note that the result will"
                              " be saved in the 'data' folder. If you decide for PDF, there is nothing more to do, "
                              " accept entering the name you wish for you file. ",
                              "-If you use the MP3 or voice-speak variant there are further questions to consider"
                              " You have to set the voice rate, language and volume for your output. "
                              " You will be asked if you want to use the default settings. "
                              " Note: When you start the program for the first time, please note to enter your "
                              " desired parameters. Otherwise the program will start with the default parameters "
                              " set by us. You can change the parameters at any time according to your preferences.",
                              "")
