### ISSUE TITLE
Change user interface 

### ISSUE THREAD

**Issue by Marco-Me** [pascalkrautm/002---Audio-News-Podcast-Generator#14]
- [x] 1. ask user to take settings recommend. And underlay recommend settings 
- [x] 2. comma separated 
- [x] 3. Save to pdf 
- [x] 4. Print for loading 
- [x] 5. URL ist in english and more sources -ü15 english sources-
- [x] 6. Explain User parameter when asking for it
- [x] 7. Everything in english language

- [x] Questions with: "art" library

**Comment by pascalkrautm** [comment]
art library implemented with starting letters

**Comment by pascalkrautm** [comment]
updated multiple keywords (not working properly). Cant provide keywords[]

**Comment by pascalkrautm** [comment]
converting to small letters added. No matter if Corona or corona anymore.

**Comment by pascalkrautm** [comment]
multiple keywords is working!

**Comment by Matadore3** [comment]
Solved: Ask user if default settings shout be used. If no ask for parameters. ("y" or "n") save settings in setting doc for next time

I think this is not final in object oriented programming

**Comment by Marco-Me** [comment]
Save as pdf or save as mp3

**Comment by pascalkrautm** [comment]
comma separated code

keywords = []
        keyword = (input("Enter comma separated topics' (eg: corona, soccer, germany)"))
        keywords.append(keyword.lower().split(","))
        print(keywords)

**Comment by pascalkrautm** [comment]
Print for loading done

**Comment by pascalkrautm** [comment]
Comma separated input is working and implemented

**Comment by pascalkrautm** [comment]
english sources ü15 implemented

**Comment by pascalkrautm** [comment]
Explain User parameter when asking for it
done

**Comment by Matadore3** [comment]
A way to save the Mp3 to the desktop: 

```
with open(r'c:/data path/generator.text.mp3', 'ab') as file: #Save to local file name
    file.write()
    file.flush()
```

Another way: 
```
import urllib.request 
`file_name`: 
urllib.request.urlretrieve(url, file_name)
```

**Comment by Matadore3** [comment]
Unfortunately, these suggested solutions are not really suitable, since the data path must always be updated manually.

**Comment by Marco-Me** [comment]
Done --> save as mp3 
Done --> Everything in english language

**Comment by Matadore3** [comment]
Done --> save as pdf

**Comment by pascalkrautm** [comment]
let the squirrel check :shipit:

**Comment by pascalkrautm** [comment]
:shipit: Squirrel check completed
