### ISSUE TITLE
Url-list

### ISSUE THREAD

**Issue by Marco-Me** [pascalkrautm/002---Audio-News-Podcast-Generator#15]
Add more url to Url-list

**Comment by pascalkrautm** [comment]
reached 30 entrys

**Comment by pascalkrautm** [comment]
This code works properly for scanning all url in URL list. 
It separates them from comma and takes each as argument. 
The amount of sources can be extended but are enough for protype.
```
file = open("url_list.txt", "r")
        self.content = file.read()
        self.url_list = self.content.split(",")
```

**Comment by Matadore3** [comment]
Update of the issue for compliance with the standards
