### ISSUE TITLE
Possible future development

### ISSUE THREAD

**Issue by Marco-Me** [pascalkrautm/002---Audio-News-Podcast-Generator#16]
Write down how to develop the program in the future.

**Comment by Marco-Me** [comment]
Not only Keyword. Instead all words with the same meaning.

**Comment by Matadore3** [comment]
Besides RSS feeds also scrape ATOM feeds

**Comment by pascalkrautm** [comment]
1. <ins>User input</ins>
- check for synonyms for the user input
- Make recommendations for keywords to search for 
- Possibility to look for given topics 
- Possibility to select more languages

2. <ins>Set options in application</ins> 
- enter save path for the MP3 and PDF file
- enter url to extend the url list

3. <ins>Output</ins>
- only show new entries
- nice formatting inside PDF file e.g. by inserting images or bulleted lists  

4. <ins>Design features</ins>
- some more design features like web interface would be great
- Implement main menu to start with 
- use python package to make parts looking better

**Comment by Matadore3** [comment]
Update of the issue for compliance with the standards
