### ISSUE TITLE
Improve speech style!

### ISSUE THREAD

**Issue by pascalkrautm** [pascalkrautm/002---Audio-News-Podcast-Generator#19]
Please make a break possible between Sentences. Maybe change "" with .

**Comment by pascalkrautm** [comment]
english speaker as standard

**Comment by Marco-Me** [comment]
Done

**Comment by Matadore3** [comment]
Issue updated to meet standards

**Comment by Matadore3** [comment]
For more information see also: #33, #13 and #34
