### ISSUE TITLE
To do --- last steps

### ISSUE THREAD

**Issue by Marco-Me** [pascalkrautm/002---Audio-News-Podcast-Generator#20]
- [x] - Solve the problem that the mp3 stores only one article
- [x] - Solve the problem that the pdf looks strange 
- [x] - Solve the problem that the url list contains not only rss feeds 
- [x] - Clean the code from not used things 
- [x] - Work on ReadMe file 
- [x] - finish the helper text

**Comment by Marco-Me** [comment]
solved the problem that the mp3 stores only one article. The Mp3 stops after the first dot in the text, so we replaced all dots with a comma and now it works.

**Comment by Marco-Me** [comment]
Helper was inserted into the questions. Still to be done is the helper text.

**Comment by Matadore3** [comment]
First proposal for the help text is now available

**Comment by pascalkrautm** [comment]
all points done

**Comment by Matadore3** [comment]
Issue updated to meet standards
