### ISSUE TITLE
while error loop implementation 

### ISSUE THREAD

**Issue by pascalkrautm** [pascalkrautm/002---Audio-News-Podcast-Generator#21]
We probably did not find all possible errors in the code. Currently the program runs without errors, therefore for future errors a loop was written, so that the flow of the program is not disturbed. If an error occurs, it should still be highlighted in the code or the user should be asked to specify a new error.

**Comment by pascalkrautm** [comment]
is implemented

**Comment by Matadore3** [comment]
Description of the issue inserted to comply with the standards
