### ISSUE TITLE
ssl line object oriented

### ISSUE THREAD

**Issue by pascalkrautm** [pascalkrautm/002---Audio-News-Podcast-Generator#25]
For simplicity, certificate verification should be disabled for connections over HTTPs

**Comment by pascalkrautm** [comment]
ssl line is object oriented

**Comment by Matadore3** [comment]
Although ssl line is object oriented, Pycharm still gives us a violation of standards. Any improvement attempt has failed

**Comment by Matadore3** [comment]
Issue updated for the purpose of standardization and description attached
