### ISSUE TITLE
Process display in BPMN

### ISSUE THREAD

**Issue by pascalkrautm** [pascalkrautm/002---Audio-News-Podcast-Generator#26]
In order to clarify the process of our code, a flowchart should be created after BPMN, which lists the logic once again

**Comment by pascalkrautm** [comment]
we just need to check the created pdf by @Marco-Me

**Comment by pascalkrautm** [comment]
first line from show helper should point back to start instead of combining "show helper and ask for keyword"

Marco-Me: No we ask only one time for the helper and not a second time

**Comment by pascalkrautm** [comment]
first choice read and default parameters wont load pickle and set as default because we have no pickle. I think first we set the default paramters to the variables and save it as a pickle?

**Comment by pascalkrautm** [comment]
we have only female voice in german language?

MarcoMe: Yes, pyttsx3 has only german female

**Comment by pascalkrautm** [comment]
Process is completely implemented

**Comment by pascalkrautm** [comment]
- [x] Draw Process
- [x] Implement in readme
- [x] Check

**Comment by Matadore3** [comment]
Updated to comply with standards Issue and added description
