### ISSUE TITLE
Rename mainfile to podgen.py

### ISSUE THREAD

**Issue by pascalkrautm** [pascalkrautm/002---Audio-News-Podcast-Generator#28]
test if startable via console @Matadore3 with windows

**Comment by Matadore3** [comment]
Performed. Program running. See also Issue #30

**Comment by pascalkrautm** [comment]
The main.py is renamed to podgen.py.
First check seems to be successfully.
System check pls see above Issue.

**Comment by pascalkrautm** [comment]
Checks for this issue done.
