### ISSUE TITLE
Scrapping with Feedparser

### ISSUE THREAD

**Issue by pascalkrautm** [pascalkrautm/002---Audio-News-Podcast-Generator#3]
- [x] Creating an url opener going through given url_list. 
- [x] Provide site code within error loop. 
- [x] looking for the xml file
- [x] saves every xml file inside list: xml_list
- [x] Provide error/succeed feedback

**Comment by Matadore3** [comment]
alternative: https://stackoverflow.com/questions/12451997/beautifulsoup-gettext-from-between-p-not-picking-up-subsequent-paragraphs

**Comment by Marco-Me** [comment]
Suggestion: Summarize cleaning code

**Comment by pascalkrautm** [comment]
alternative for cleaning code in one:

```
var str  = "hallo, wie geht es Dir, ich/oder Du; blinde Kuh";
var reg  = /[/.;, ]/;

while(reg.exec(str)){
 str = str.replace(reg,"");
}
alert(str);
```

**Comment by pascalkrautm** [comment]
Still need more than one Keyword. At the moment only one is working

**Comment by Matadore3** [comment]
We decided against Beautiful Soup and for Feedparser because Beautiful Soup needs several modules to work
