### ISSUE TITLE
Please Check Codes in Readme

### ISSUE THREAD

**Issue by Matadore3** [pascalkrautm/002---Audio-News-Podcast-Generator#32]
The codes we have in the readme should be final checked for actuality. Since the last check there were small adjustments to the code

**Comment by pascalkrautm** [comment]
I have added the summary section, also in table of contents, codes within the "problems to deal with" section, updated the codes with all new code changes, corrected some capitalization

**Comment by Matadore3** [comment]
Code and new content I have checked and hereby release. The codes in the readme match those in the respective folders.

What do you say @Marco-Me ?

**Comment by Marco-Me** [comment]
Checked 👍
