### ISSUE TITLE
Language settings

### ISSUE THREAD

**Issue by pascalkrautm** [pascalkrautm/002---Audio-News-Podcast-Generator#33]
We need the right language setting for every decision knote. 

- [x] English male, Voice ID 0
- [x] English female Voice ID 10
- [x] german female Voice ID 4

@Matadore3  can you confirm this setting?

**Comment by Matadore3** [comment]
If we code a loop, which distinguishes between Mac and Windows, and directly enter the keys of the languages, it works better 

See also: #13, #33
