### ISSUE TITLE
The App has to separate between MacOS and Windows while giving the language output

### ISSUE THREAD

**Issue by pascalkrautm** [pascalkrautm/002---Audio-News-Podcast-Generator#34]
Let me check this one more time. I think iam done with this but need some further tests.

- [x] Working on windows
- [x] working on MacOS

**Comment by pascalkrautm** [comment]
#33 will regard the same topic. Maybe we can close #33 or answer both

**Comment by Matadore3** [comment]
This topic is also listed here:  #13

**Comment by pascalkrautm** [comment]
Check is done. See also mentioned issues.
