### ISSUE TITLE
Document according to TDSP (Team Data Science Process)

### ISSUE THREAD

**Issue by Eren1905** [pascalkrautm/002---Audio-News-Podcast-Generator#7]
Both the code and our readme file build according to CAPM

**Comment by Matadore3** [comment]
other possibility: TDSP (Team Data Science Process) -> https://docs.microsoft.com/de-de/azure/machine-learning/team-data-science-process/overview

**Comment by Matadore3** [comment]
The team decided to create the whole thing according to the idea of TDSP (Team Data Science Process). Already last week, the first proposal was submitted, but it was found to be unacceptable by all parties involved. The first revision of the readme file was already done yesterday. Thereby the Business Understanding, the Task, the Achievment and the Modeling were rebooted. A number of topics were added to the first revision today. These include for example: Class Converter Completed, content extended to the other classes, Business Understanding updated, Data Understanding extended, Table of Contents inserted, Links inserted, Pictures inserted, Spelling, General editing activities.

**Comment by Matadore3** [comment]
The following topics are still pending: 

- [X] Class Converter() quality assurance 
- [X] Insert decision tree to the systematics of the tree 
- [X] visualize process flow 
- [x] Check for grammar and spelling
- [X] The links in the table of contents do not work properly yet, please fix them here

**Comment by Matadore3** [comment]
the following things have already been done: 
- Insert decision tree to the systematics of the tree (see chapter 6: Display the Process)
- visualize process flow (see: Chapter 1: Task/ Working Process) 
- Some screenshots were not displayed, was fixed 
- We assume that the links in the document do not work in Pycharm because we have the editor mode there. Links work on Github
- Class Converter() quality assurance

**Comment by Matadore3** [comment]
The following topics are still pending (new):
- Check for grammar and spelling #29 
- continue searching for the link problem in pycharm

**Comment by Matadore3** [comment]
Please update class: Converter in readme!

**Comment by Matadore3** [comment]
The links in the table of contents work on github but not on Pycharm. We assume it is because we are in editor mode in pycharm and due to this, there is no jumping within a document. On github the links are correct and working

**Comment by Matadore3** [comment]
From my side the final version is now available. 

What's your situation? @Marco-Me @pascalkrautm

**Comment by pascalkrautm** [comment]
From my side we are done 🥇 💯

**Comment by Marco-Me** [comment]
Also from my side we are done!
