### ISSUE TITLE
Search Key Words and Convers into text file. 

### ISSUE THREAD

**Issue by Eren1905** [pascalkrautm/002---Audio-News-Podcast-Generator#8]
Filter XLM codes by key words and display them as a text file.

**Comment by Eren1905** [comment]
New Issue

**Comment by Matadore3** [comment]
Key word search is executed during parsing

**Comment by pascalkrautm** [comment]
done

**Comment by Matadore3** [comment]
The conversion to txt is no longer done. The code is able to read or save the output (as pdf) after it has been cleaned up during the scraping process.
